#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
TEMP_MENU=$(mktemp)
trap 'rm -f "$TEMP_MENU"' EXIT

"$ROOT_DIR/node_modules/.bin/esbuild" "$ROOT_DIR/gtag.ts" \
  --bundle=false \
  --format=iife \
  --platform=neutral \
  --target=es2020 \
  --outfile="$TEMP_MENU"

{
  printf '%s\n' '// Generated by npm run build:agent. Do not edit this file directly.'
  printf '%s\n' '// Load order: bundled frida-il2cpp-bridge, then the menu script.'
  cat "$ROOT_DIR/frida-il2cpp-bridge.js"
  printf '\n;\n'
  cat "$TEMP_MENU"
} > "$ROOT_DIR/android/agent.js"

printf 'Built %s (%s bytes)\n' "$ROOT_DIR/android/agent.js" "$(wc -c < "$ROOT_DIR/android/agent.js")"
